import torch
import numpy as np

TEST_GO_TO_TREE = ["You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to tree\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: ",
                      "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to tree\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: ",
                      "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to tree\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 1\n\nYour success rate is: ",
                      "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to tree\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 1\n\nYour success rate is: ",
                      "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to tree\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 1 step to your north-west\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: ",
                      "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to tree\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 1 step to your north\n\nYou face tree at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: "]

TESTS_COLLECT_WOOD = ["You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: collect wood\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: ",
                      "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: collect wood\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: ",
                      "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: collect wood\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 1\n\nYour success rate is: ",
                      "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: collect wood\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 1\n\nYour success rate is: ",
                      "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: collect wood\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 1 step to your north-west\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: ",
                      "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: collect wood\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 1 step to your north\n\nYou face tree at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: "]

TESTS_PLACE_TABLE = ["You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: place table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: ",
                     "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: place table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: ",
                     "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: place table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 1\n\nYour success rate is: ",
                     "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: place table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 1\n\nYour success rate is: ",
                     "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: place table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 2\n\nYour success rate is: ",
                     "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: place table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 2\n\nYour success rate is: ",
                     "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: place table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n- stone 1 step to your west\n- path 2 steps to your south-west\n- tree 6 steps to your north-west\n- coal 2 steps to your west\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: ",
                     "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: place table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 1 step to your north\n\nYou face tree at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: ",
                     "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: place table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n- table 1 step to your north\n\nYou face table at your front.\n\nYou have nothing in your inventory.\n\nYou placed table at (32,31)\n\nYour success rate is: ",
                     "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: place table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- coal 1 step to your north\n\nYou face coal at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: "
                     ]

TEST_GO_TO_TABLE = ["You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: ",
                    "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: ",
                    "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 1\n\nYour success rate is: ",
                    "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 1\n\nYour success rate is: ",
                    "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 2\n\nYour success rate is: ",
                    "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n- table 2 steps to your north\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYou placed table at (32, 30)\n\nYour success rate is: ",
                    "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n- table 2 steps to your north\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYou placed table at (32, 30)\n\nYour success rate is: ",
                    "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYou placed table at (20,21)\n\nYour success rate is: ",
                    "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYou placed table at (20,21)\n\nYour success rate is: ",
                    "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n- table 1 step to your north\\n\\nYou face table at your front.\n\nYou have nothing in your inventory.\n\nYou placed table at (32, 31)\n\nYour success rate is: ",
                    "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: go to table\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n- table 1 step to your north\n\nYou face table at your front.\n\nYou have nothing in your inventory.\n\nYou placed table at (32, 31)\n\nYour success rate is: "
                    ]

TESTS_MAKE_WOOD_PICKAXE = ["You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 1\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 1\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 2\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 2\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 3\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 3\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n- table 2 steps to your north\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYou placed table at (32, 30)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n- table 2 steps to your north\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYou placed table at (32, 30)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n- table 2 steps to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 1\n\nYou placed table at (32, 30)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n- table 2 steps to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 1\n\nYou placed table at (32, 30)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n- table 2 steps to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 2\n\nYou placed table at (32, 30)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n- table 2 steps to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 2\n\nYou placed table at (32, 30)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n- table 2 steps to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 3\n\nYou placed table at (32, 30)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n- table 2 steps to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 3\n\nYou placed table at (32, 30)\n\nYour success rate is:",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYou placed table at (20,21)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYou have nothing in your inventory.\n\nYou placed table at (20,21)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 1\n\nYou placed table at (20,21)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 1\n\nYou placed table at (20,21)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 2\n\nYou placed table at (20,21)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 2\n\nYou placed table at (20,21)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 3\n\nYou placed table at (20,21)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n\nYou face grass at your front.\n\nYour inventory:\n- wood: 3\n\nYou placed table at (20,21)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n- table 1 step to your north\\n\\nYou face table at your front.\n\nYou have nothing in your inventory.\n\nYou placed table at (32, 31)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n- table 1 step to your north\n\nYou face table at your front.\n\nYou have nothing in your inventory.\n\nYou placed table at (32, 31)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n- table 1 step to your north\n\nYou face table at your front.\n\nYour inventory:\n- wood: 1\n\nYou placed table at (32, 31)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n- table 1 step to your north\n\nYou face table at your front.\n\nYour inventory:\n- wood: 1\n\nYou placed table at (32, 31)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n- table 1 step to your north\n\nYou face table at your front.\n\nYour inventory:\n- wood: 2\n\nYou placed table at (32, 31)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n- table 1 step to your north\n\nYou face table at your front.\n\nYour inventory:\n- wood: 2\n\nYou placed table at (32, 31)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your north\n- table 1 step to your north\n\nYou face table at your front.\n\nYour inventory:\n- wood: 3\n\nYou placed table at (32, 31)\n\nYour success rate is: ",
                           "You are playing a Minecraft like game.\nYour task is to evaluate your success rate for the goal: make wood pickaxe\n\nYour coordinates: (32,32)\n\nYou see:\n- grass 1 step to your west\n- tree 6 steps to your north-west\n- table 1 step to your north\n\nYou face table at your front.\n\nYour inventory:\n- wood: 3\n\nYou placed table at (32, 31)\n\nYour success rate is: "
                           ]

def test_high_level_sr_estimator(lm):
    estimated_sr = dict()
    estimated_lp = dict()
    for test_list, tsk in zip([TESTS_COLLECT_WOOD, TESTS_PLACE_TABLE, TESTS_MAKE_WOOD_PICKAXE], ["collect_wood", "place_table", "make_wood_pickaxe"]):
        sigm = torch.nn.Sigmoid()

        output = lm.custom_module_fns(['sr_hl_estimator_delayed'],
                                      contexts=test_list,
                                      candidates=[[" "] for _ in range(len(test_list))],
                                      require_grad=False, peft_adapter="sr_HL_adapters_delayed", pad_contexts=False)
        sr_delayed = sigm(torch.stack([_o['sr_hl_estimator_delayed']["sr_hl_estimated"] for _o in output]).squeeze()).detach().cpu().numpy()

        output = lm.custom_module_fns(['sr_hl_estimator'],
                                       contexts=test_list,
                                       candidates=[[" "] for _ in range(len(test_list))],
                                       require_grad=False,
                                       peft_adapter='sr_HL_adapters',
                                       add_eos_on_candidates=False, pad_contexts=False)
        # logits_sr = torch.stack([_o['sr_hl_estimator']["sr_hl_estimated"] for _o in output])
        sr = sigm(torch.stack([_o["sr_hl_estimator"]["sr_hl_estimated"] for _o in output]).squeeze()).detach().cpu().numpy()
        lp = np.abs(sr - sr_delayed)
        lp[lp < 0.01] = 0.0

        estimated_sr[tsk] = sr
        estimated_lp[tsk] = lp
    print("\nHL SR Estimator results:")
    print("Estimated success rate for collect wood:\n{}".format(estimated_sr["collect_wood"]))
    print("Estimated success rate for place table:\n{}".format(estimated_sr["place_table"]))
    print("Estimated success rate for make wood pickaxe:\n{}".format(estimated_sr["make_wood_pickaxe"]))
    print("\nHL LP Estimator results:")
    print("Estimated lp for collect wood:\n{}".format(estimated_lp["collect_wood"]))
    print("Estimated lp for place table:\n{}".format(estimated_lp["place_table"]))
    print("Estimated lp for make wood pickaxe:\n{}".format(estimated_lp["make_wood_pickaxe"]))
    return estimated_sr, estimated_lp

