DICTIONARY_STR_TO_ID_0={'do nothing':0,
'move left':1,
'move right':2,
'move up':3,
'move down':4,
'sleep':18,
'eat zombie':0,
'eat skeleton':0,
'eat cow':9,
'eat tree':0,
'eat bush':0,
'eat stone':0,
'eat coal':0,
'eat iron':0,
'eat diamond':0,
'eat water':0,
'eat grass':0,
'eat crafting table':0,
'eat furnace':0,
'eat plant':5,
'eat wood pickaxe':0,
'eat stone pickaxe':0,
'eat iron pickaxe':0,
'eat wood sword':0,
'eat stone sword':0,
'eat iron sword':0,
'attack zombie':6,
'attack skeleton':7,
'attack cow':8,
'attack tree':0,
'attack bush':0,
'attack stone':0,
'attack coal':0,
'attack iron':0,
'attack diamond':0,
'attack water':0,
'attack grass':0,
'attack crafting table':0,
'attack furnace':0,
'attack plant':0,
'attack wood pickaxe':0,
'attack stone pickaxe':0,
'attack iron pickaxe':0,
'attack wood sword':0,
'attack stone sword':0,
'attack iron sword':0,
'chop zombie':0,
'chop skeleton':0,
'chop cow':0,
'chop tree':10,
'chop bush':11,
'chop stone':0,
'chop coal':0,
'chop iron':0,
'chop diamond':0,
'chop water':0,
'chop grass':17,
'chop crafting table':0,
'chop furnace':0,
'chop plant':0,
'chop wood pickaxe':0,
'chop stone pickaxe':0,
'chop iron pickaxe':0,
'chop wood sword':0,
'chop stone sword':0,
'chop iron sword':0,
'mine zombie':0,
'mine skeleton':0,
'mine cow':0,
'mine tree':0,
'mine bush':0,
'mine stone':12,
'mine coal':13,
'mine iron':14,
'mine diamond':15,
'mine water':0,
'mine grass':0,
'mine crafting table':0,
'mine furnace':0,
'mine plant':0,
'mine wood pickaxe':0,
'mine stone pickaxe':0,
'mine iron pickaxe':0,
'mine wood sword':0,
'mine stone sword':0,
'mine iron sword':0,
'drink zombie':0,
'drink skeleton':0,
'drink cow':0,
'drink tree':0,
'drink bush':0,
'drink stone':0,
'drink coal':0,
'drink iron':0,
'drink diamond':0,
'drink water':16,
'drink grass':0,
'drink crafting table':0,
'drink furnace':0,
'drink plant':0,
'drink wood pickaxe':0,
'drink stone pickaxe':0,
'drink iron pickaxe':0,
'drink wood sword':0,
'drink stone sword':0,
'drink iron sword':0,
'place zombie':0,
'place skeleton':0,
'place cow':0,
'place tree':0,
'place bush':0,
'place stone':19,
'place coal':0,
'place iron':0,
'place diamond':0,
'place water':0,
'place grass':0,
'place crafting table':20,
'place furnace':21,
'place plant':22,
'place wood pickaxe':0,
'place stone pickaxe':0,
'place iron pickaxe':0,
'place wood sword':0,
'place stone sword':0,
'place iron sword':0,
'make zombie':0,
'make skeleton':0,
'make cow':0,
'make tree':0,
'make bush':0,
'make stone':0,
'make coal':0,
'make iron':0,
'make diamond':0,
'make water':0,
'make grass':0,
'make crafting table':20,
'make furnace':21,
'make plant':0,
'make wood pickaxe':23,
'make stone pickaxe':24,
'make iron pickaxe':25,
'make wood sword':26,
'make stone sword':27,
'make iron sword':28}
